backend:
  name: git-gateway
  branch: main

media_folder: "src/blog/images"
public_folder: "/blog/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/blog/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["post"]
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
